# Generated by Django 5.1.7 on 2025-04-09 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HabitModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TimeField(max_length=200, verbose_name='Название привычки')),
                ('location', models.CharField(max_length=400, verbose_name='место выполнеия привычки')),
                ('perform_time', models.TimeField(verbose_name='когда выполнять привичку')),
                ('substance', models.CharField(max_length=2000, verbose_name='содержание привычки')),
                ('is_pleasant', models.BooleanField(verbose_name='признак приятной привычки')),
                ('period', models.DateField(verbose_name='периодичность выполнения')),
                ('lasting_time', models.TimeField(verbose_name='длительность выполнения')),
            ],
            options={
                'verbose_name': 'Привычка',
                'verbose_name_plural': 'Привычки',
            },
        ),
        migrations.CreateModel(
            name='RewordModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='название вознаграждения')),
                ('description', models.CharField(max_length=1000, verbose_name='описнаие вознаграждения')),
            ],
            options={
                'verbose_name': 'Вознаграждение',
                'verbose_name_plural': 'Вознаграждения',
            },
        ),
    ]
