# Generated by Django 5.1.7 on 2025-04-09 15:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('habit_tracker', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='habitmodel',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user', to=settings.AUTH_USER_MODEL, verbose_name='Автор привички'),
        ),
        migrations.AddField(
            model_name='rewordmodel',
            name='habit',
            field=models.ManyToManyField(to='habit_tracker.habitmodel', verbose_name=''),
        ),
        migrations.AddField(
            model_name='habitmodel',
            name='reword',
            field=models.ManyToManyField(to='habit_tracker.rewordmodel', verbose_name='вознаграждение'),
        ),
    ]
