# Generated by Django 5.1.7 on 2025-04-11 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('habit_tracker', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='habitmodel',
            name='reword',
            field=models.ManyToManyField(blank=True, to='habit_tracker.rewordmodel', verbose_name='вознаграждение'),
        ),
        migrations.AlterField(
            model_name='rewordmodel',
            name='habit',
            field=models.ManyToManyField(blank=True, to='habit_tracker.habitmodel', verbose_name='связанная привычка'),
        ),
    ]
