# Generated by Django 5.1.7 on 2025-04-11 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('habit_tracker', '0003_alter_habitmodel_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='habitmodel',
            name='name',
            field=models.CharField(max_length=200, verbose_name='Название привычки'),
        ),
    ]
