# Generated by Django 5.1.7 on 2025-05-13 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("habit_tracker", "0003_habitmodel_created_at"),
    ]

    operations = [
        migrations.AlterField(
            model_name="habitmodel",
            name="period",
            field=models.CharField(
                choices=[
                    ("ежедневно", "ежедневно"),
                    ("каждые два дня", "каждые два дня"),
                    ("еженедельно", "еженедельно"),
                ],
                default="ежедневно",
                max_length=20,
                verbose_name="периодичность выполнения",
            ),
        ),
    ]
