# Generated by Django 5.1.7 on 2025-04-11 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('habit_tracker', '0004_alter_habitmodel_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='habitmodel',
            name='perform_time',
            field=models.TimeField(null=True, verbose_name='когда выполнять привичку'),
        ),
        migrations.AlterField(
            model_name='habitmodel',
            name='period',
            field=models.PositiveIntegerField(null=True, verbose_name='периодичность выполения'),
        ),
    ]
