# Generated by Django 5.1.7 on 2025-04-13 07:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('habit_tracker', '0005_alter_habitmodel_perform_time_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rewordmodel',
            name='habit',
        ),
        migrations.RemoveField(
            model_name='habitmodel',
            name='reword',
        ),
        migrations.AddField(
            model_name='habitmodel',
            name='reword',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='habit_tracker.rewordmodel', verbose_name='вознаграждение'),
        ),
    ]
