# Generated by Django 5.1.7 on 2025-04-13 08:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('habit_tracker', '0006_remove_rewordmodel_habit_remove_habitmodel_reword_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='habitmodel',
            name='pleasant_hab',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='habit_tracker.habitmodel', verbose_name='приятная привычка'),
        ),
    ]
